$activeBorderColor = rgb(c4a7e7)
$inactiveBorderColor = rgba(26233abb)

general {
    border_size = 1
    gaps_in = 5
    gaps_out = 8

    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor
}

decoration {
    shadow {
        enabled = true
        render_power = 4
        range = 6
        color = rgba(060b16aa)
        offset = 5 5
    }

    blur {
        enabled = true
        size = 1
        passes = 4
        contrast = 1.1
        brightness = 1.1
        vibrancy = 0.2
        vibrancy_darkness = 0.2
        noise = 0.03
        ignore_opacity = true
        new_optimizations = true
    }

    dim_inactive = true
    dim_strength = 0.1
}

animations {
    enabled = true

    bezier = calm, 0.25, 0.9, 0.35, 1

    animation = windows, 1, 4, calm
    animation = windowsIn, 1, 4, calm
    animation = windowsOut, 1, 3, calm
    animation = windowsMove, 1, 4, calm
    animation = fade, 1, 3, calm
    animation = fadeIn, 1, 3, calm
    animation = fadeOut, 1, 2, calm
    animation = layers, 1, 3, calm
    animation = layersIn, 1, 3, calm
    animation = layersOut, 1, 2, calm
    animation = workspaces, 1, 4, calm
}

windowrule = size 960 640, match:class com.mitchellh.ghostty
windowrule = center on, match:class com.mitchellh.ghostty

windowrule = opacity 1.0 override, match:content game

layerrule = blur on, match:namespace walker
layerrule = ignore_alpha 0, match:namespace walker
layerrule = blur on, match:namespace waybar
layerrule = blur on, match:namespace notifications
layerrule = ignore_alpha 0, match:namespace notifications
layerrule = blur on, match:namespace vicinae
layerrule = blur on, match:namespace swayosd
layerrule = ignore_alpha 0.1, match:namespace waybar
layerrule = ignore_alpha 0.1, match:namespace vicinae
